spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/sdtp-service
    password: postgres
    initialization-mode: always
    hikari:
      minimumIdle: 5
      maximumPoolSize: 100
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: 'HikariPoolProjects'
      auto-commit: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        show-sql: false
        connection:
          provider_disables_autocommit: true